FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node

RUN mkdir /opt/flowfuse-device
RUN npm install -f @flowfuse/device-agent
COPY device.yml /opt/flowfuse-device/device.yml

CMD ["flowfuse-device-agent"]

